{% set version = "1.07" %}

package:
  name: wmctrl-cli
  version: {{ version }}

source:
  url: https://deb.debian.org/debian/pool/main/w/wmctrl/wmctrl_{{ version }}.orig.tar.gz
  sha256: d78a1efdb62f18674298ad039c5cbdb1edb6e8e149bb3a8e3a01a4750aa3cca9
  patches:
    - wmctrl.patch

build:
  skip: true  # [win]
  number: 0
  detect_binary_files_with_prefix: true
  ignore_run_exports:
    - xorg-libsm
    - xorg-libice

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - gettext
    - pkg-config
    - make
    - autoconf
    - automake
    - libtool
  host:
    - glib
    - xorg-libx11
    - xorg-libxmu
    - xorg-libsm
    - xorg-libice

test:
  commands:
    - wmctrl --version

about:
  home: http://tripie.sweb.cz/utils/wmctrl/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Unix command-line tool to interact with an EWMH/NetWM-compatible X Window Manager.

extra:
  recipe-maintainers:
    - ehfd
